---
title: "About Me"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

## Currently

I'm an applied statistician and data scientist at [Cone Health](https://www.conehealth.com/) in Greensboro, NC. I come to the world of healthcare after nearly ten years in manufacturing and two in higher education. My interests are in: 

* Bayesian Inference

* Causal Inference

* Survey Analysis

* Applied Machine Learning and Prediction

* Simulation and Optimization

* Infectious Disease Modelling

Additionally, I am an advocate for improving mobility. In my spare time I volunteer as a member of the Winston-Salem Transportation Coalition where we advocate for better public transit. I employ data science techniques in order to quantify and shed light on the issues. 

You can read more about my work [here](presentations.html). Additionally, I maintain a site regarding local politics and economic analysis. You can read that [here](https://www.nctriadresearch.com/).

## Before

I came into statistics and data science from chemical engineering (which is what I studied at University). I also minored in philosophy and wrote my honors thesis in the English department.

After graduation I worked in industrial engineering at Michelin North America in plant industrial engineering and continuous improvement and at the central level in industrial engineering, project management and decision support and analysis.

It you want to learn more, check out my resume [here](docs/DeWittResume.pdf).

<details>
<summary><h2>Short Bio</h2> </summary>
Michael DeWitt is an applied statistician and data scientist working in health care analytics and infectious disease modeling at Cone Health, one of the largest healthcare networks in North Carolina. Prior to healthcare, Michael has over ten years of experience in higher education analytics and manufacturing. His specialties are Bayesian inference, hierarchical modeling, survey design and analysis,  simulation and optimization, network analysis, and applied predictive modeling. He holds a bachelor's degree in Chemical Engineering from Clemson University and a Master's Degree in Statistics from North Carolina State University.
</details>