---
title:"My Work"
---

## presentations

This is a non-exhaustive list of presentations that I have given.

* **Designing a Student Retention Model**,  _North Carolina Independent Colleges and Universities Institutional Research Directors Meeting_, October 2018

* **Does My Instructor Look Like Me: A Multi-Institution Look at Implicit Bias in Grading**,  _Southern Association for Institutional Research_, October 2018

* [**Comparing Two Groups: Effect Sizes**](https://docs.google.com/presentation/d/e/2PACX-1vTACUkOIFra4TqEvaQUCakpsYk7KgIRBdyo14hLJ798GiPb8Z4bY0YlgvcJoj1yoDc1_9wtUXqOKbii/pub?start=false&loop=false&delayms=3000),  _Wake Forest University Business Analytics Team_, September 2018

* [**Comparing Two Groups: T-Test**](docs/2018-08_BAI_t-test.pdf), _Wake Forest University Business Analytics Team_, August 2018

* [**Introduction to R**](https://github.com/medewitt/intro_to_r/blob/master/presentations/intro_presentation.pdf), _Wake Forest University Professional Development_, March 2018

* [**Overview of Distributions**](docs/2018-02_BAI_distributions.pdf), _Wake Forest University Business Analytics Team_, February 2018

* [**Measures of Central Tendency**](docs/2017-12_BAI_central_tendency.pdf), _Wake Forest University Business Analytics Team_, December 2017

* **Graphing Different Kinds of Data**, _Wake Forest University Business Analytics Team_, November 2017

## technical papers

* [**Office of Institutional Research Survey Methodology**](https://prod.wp.cdn.aws.wfu.edu/sites/202/2018/05/oir_survey_methodology.pdf), _Wake Forest University_, May 2018

## publications

* [**Analysis of the Winston-Salem Public Transit System**](http://www.virginiapolicyreview.org/blog/analysis-of-the-winston-salem-public-transit-system) _Virginia Policy Review_, October 2018

## manuscript

I'm currently working on a manuuscript that focuses on application of data science to Institutional Research. This is trying to distill my experience on modeling and workflow into one reference. Still a work in progress, but the draft is below:

* [**Data Science for Institutional Research (DS4IR)**](ds4ir)

## public comment

This section represents any public analysis that has been presented to any public bodies.

* [**Winston-Salem Public Transit Analysis**](https://michaeldewittjr.com/bus_analysis/) by Michael DeWitt, Phillip Summers, Jeff Bloomfield, Keena Moore, Megan Irby, _Winston-Salem City Council_, September 2018

## applications

This sections represents public facing applications.

* [**Winston-Salem Police Department Tracker**](https://mdewitt.shinyapps.io/wspd_scanner/) October 2018

* [**Algorithmic Bias Simulator**](https://mdewitt.shinyapps.io/bias_simulation/) February 2019

## patents

FR Appl. No. 18/51018 filed 7 February 2018 (N/R 2017PAT00317FR) : Procede d’identifier, gerer et réincorporer les produits complexes comme les produits valorises (_applied_)

FR Appl. No. 18/51019 filed 7 February 2018 (N/R 2017PAT00431FR) : Systeme d’identifier, gerer et reincorporer les produits complexes comme les produits valorises (_applied_)